#!/usr/bin/env python3
"""Generate the KLayout DRC layer definitions from the Calibre DRC deck.

Parses the "LAYER MAP <l> DATATYPE|TEXTTYPE <d> <id>" / "LAYER <name> <id>"
pairs of the Calibre (TVF/SVRF) runset and writes a KLayout DRC include file
with one variable per Calibre layer. Variable names are the Calibre names
lowercased (Ruby locals must start lowercase), e.g. MET1o -> met1o.

Usage:
  python3 calibre_layers_to_klayout_drc.py \
      ../icsprout55-pdk/pv/DRC/ICsprout_CalDRC_55LLULP1233_REV1_0_OS.drc \
      ../icsprout55/libs.tech/klayout/tech/rule_decks/layers_def.drc
"""

import re
import sys
from collections import OrderedDict

MAP_RE = re.compile(r'^\s*LAYER\s+MAP\s+(\d+)\s+(DATATYPE|TEXTTYPE)\s+(\d+)\s+(\d+)')
NAME_RE = re.compile(r'^\s*LAYER\s+([A-Za-z_]\w*)\s+(\d+)\s*$')

HEADER = """\
# frozen_string_literal: true

#=========================================================================================
# Copyright 2026 Ckristian Duran
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=========================================================================================

#================================================
#------------- LAYERS DEFINITIONS ---------------
#================================================
# AUTO-GENERATED by hacking/calibre_layers_to_klayout_drc.py from
# {source}
# Do not edit by hand. Names are the Calibre layer names, lowercased.

logger.info('Read in polygons from layers.')

def get_polygons(layer, data_type)
  ps = polygons(layer, data_type)
  $run_mode == 'deep' ? ps : ps.merged
end

"""


def parse(path):
    """Return OrderedDict name -> list of (layer, kind, datatype)."""
    by_id = {}
    layers = OrderedDict()
    with open(path, encoding='latin-1') as f:
        for line in f:
            m = MAP_RE.match(line)
            if m:
                lay, kind, dt, lid = m.groups()
                by_id.setdefault(lid, []).append((int(lay), kind, int(dt)))
                continue
            m = NAME_RE.match(line)
            if m and m.group(2) in by_id:
                layers[m.group(1)] = by_id[m.group(2)]
    return layers


def main(src, dst):
    layers = parse(src)
    out = [HEADER.format(source=src)]
    for name, maps in layers.items():
        var = name.lower()
        drawn = [(l, d) for l, k, d in maps if k == 'DATATYPE']
        texts = [(l, d) for l, k, d in maps if k == 'TEXTTYPE']
        if drawn:
            (l, d), = drawn
            out.append(f"{var} = get_polygons({l}, {d})")
        else:
            (l, d), = texts
            out.append(f"{var} = labels({l}, {d})")
    out.append(f"\nlogger.info('Defined {len(layers)} Calibre layers.')\n")
    with open(dst, 'w') as f:
        f.write('\n'.join(out))
    print(f"Wrote {len(layers)} layers to {dst}")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
