meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable magic DRC
    #Magic.DRC: null
    #Checker.MagicDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null
    
    # Save time
    #OpenROAD.IRDropReport: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

    # Use Magic.Filler instead of KLayout.Filler
    # This can help in some cases where the target
    # density cannot be met using KLayout.
    #KLayout.Filler: Magic.Filler

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::src/chip_top.sv
- dir::src/chip_core.sv

VERILOG_DEFINES: [FUNCTIONAL]

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    "bidirs\\[0\\].bidir_pad",
    "bidirs\\[1\\].bidir_pad",
    "bidirs\\[2\\].bidir_pad",
    "bidirs\\[3\\].bidir_pad",
    "bidirs\\[4\\].bidir_pad",
    "bidirs\\[5\\].bidir_pad",
    "bidirs\\[6\\].bidir_pad",
    "bidirs\\[7\\].bidir_pad"
]

PAD_EAST: [
    clk_pad,
    rst_n_pad,
    "vdd_pads\\[0\\].vdd_pad",
    "vss_pads\\[0\\].vss_pad"
]

PAD_NORTH: [
    "outputs\\[7\\].output_pad",
    "outputs\\[6\\].output_pad",
    "outputs\\[5\\].output_pad",
    "outputs\\[4\\].output_pad",
    "outputs\\[3\\].output_pad",
    "outputs\\[2\\].output_pad",
    "outputs\\[1\\].output_pad",
    "outputs\\[0\\].output_pad",
    
    "iovdd_pads\\[0\\].iovdd_pad",
    "iovss_pads\\[0\\].iovss_pad"
]

PAD_WEST: [
    "inputs\\[9\\].input_pad",
    "inputs\\[8\\].input_pad",
    "inputs\\[7\\].input_pad",
    "inputs\\[6\\].input_pad",
    "inputs\\[5\\].input_pad",
    "inputs\\[4\\].input_pad",
    "inputs\\[3\\].input_pad",
    "inputs\\[2\\].input_pad",
    "inputs\\[1\\].input_pad",
    "inputs\\[0\\].input_pad"
]

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk_XI_PAD
CLOCK_NET: clk_pad/XC

CLOCK_PERIOD: 20

# Floorplanning
FP_SIZING: absolute
# 1.6mmx1.6mm as an example
# For core area, we reduce the IO size, and some for the ring
# 12.45*2 + 10*2 + 5 + 130 ~= 180
DIE_AREA: [0, 0, 1600, 1600]
CORE_AREA: [180, 180, 1420, 1420]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 10
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CORE_RING: True

PDN_CORE_RING_VWIDTH: 10
PDN_CORE_RING_HWIDTH: 10
# TODO: Check if this ensures enough spacing
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

# Remember to run the demo_counter!
MACROS:
  counter:
    gds:
      - dir::../demo_counter/runs/debug_ics/final/gds/counter.gds
    lef:
      - dir::../demo_counter/runs/debug_ics/final/lef/counter.lef
    vh:
      - dir::../demo_counter/runs/debug_ics/final/vh/counter.vh
    lib:
      "*_ff_n40C_1v32":
        - dir::../demo_counter/runs/debug_ics/final/lib/nom_ff_n40C_1v32/counter__nom_ff_n40C_1v32.lib
      "*_ss_125C_1v08":
        - dir::../demo_counter/runs/debug_ics/final/lib/nom_ss_125C_1v08/counter__nom_ss_125C_1v08.lib
      "*_tt_025C_1v20":
        - dir::../demo_counter/runs/debug_ics/final/lib/nom_tt_025C_1v20/counter__nom_tt_025C_1v20.lib
    instances:
      # Make sure to specify the macros in pdn_cfg.tcl
      i_chip_core.counter_1:
        location: [390, 390]
        orientation: N
      i_chip_core.counter_2:
        location: [860, 390]
        orientation: N

# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- "i_chip_core.counter_1 VDD VSS VDD VSS"
- "i_chip_core.counter_2 VDD VSS VDD VSS"

# Custom PDN config to connect to SRAMs
PDN_CFG: dir::pdn_cfg.tcl
